/*
 * Gantt Chart Schedule API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GanttChartScheduleApi);
  }
}(this, function(expect, GanttChartScheduleApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('EModelEvent', function() {
      beforeEach(function() {
        instance = GanttChartScheduleApi.EModelEvent;
      });

      it('should create an instance of EModelEvent', function() {
        // TODO: update the code to test EModelEvent
        expect(instance).to.be.a('object');
      });

      it('should have the property ADD', function() {
        expect(instance).to.have.property('ADD');
        expect(instance.ADD).to.be("ADD");
      });

      it('should have the property CHANGE', function() {
        expect(instance).to.have.property('CHANGE');
        expect(instance.CHANGE).to.be("CHANGE");
      });

      it('should have the property REMOVE', function() {
        expect(instance).to.have.property('REMOVE');
        expect(instance.REMOVE).to.be("REMOVE");
      });

    });
  });

}));
