/*
 * Gantt Chart Schedule API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GanttChartScheduleApi);
  }
}(this, function(expect, GanttChartScheduleApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GanttChartModelEvent', function() {
      beforeEach(function() {
        instance = new GanttChartScheduleApi.GanttChartModelEvent();
      });

      it('should create an instance of GanttChartModelEvent', function() {
        // TODO: update the code to test GanttChartModelEvent
        expect(instance).to.be.a(GanttChartScheduleApi.GanttChartModelEvent);
      });

      it('should have the property modelEvent (base name: "modelEvent")', function() {
        // TODO: update the code to test the property modelEvent
        expect(instance).to.have.property('modelEvent');
        // expect(instance.modelEvent).to.be(expectedValueLiteral);
      });

      it('should have the property oldTask (base name: "oldTask")', function() {
        // TODO: update the code to test the property oldTask
        expect(instance).to.have.property('oldTask');
        // expect(instance.oldTask).to.be(expectedValueLiteral);
      });

      it('should have the property newTask (base name: "newTask")', function() {
        // TODO: update the code to test the property newTask
        expect(instance).to.have.property('newTask');
        // expect(instance.newTask).to.be(expectedValueLiteral);
      });

    });
  });

}));
