/*
 * Gantt Chart Schedule API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient.js';
import EModelEvent from './model/EModelEvent.js';
import GanttChartModelEvent from './model/GanttChartModelEvent.js';
import ScheduledTask from './model/ScheduledTask.js';
import SerializableColor from './model/SerializableColor.js';
import DefaultApi from './api/DefaultApi.js';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GanttChartScheduleApi = require('index'); // See note below*.
* var xxxSvc = new GanttChartScheduleApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GanttChartScheduleApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GanttChartScheduleApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GanttChartScheduleApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The EModelEvent model constructor.
     * @property {module:model/EModelEvent}
     */
    EModelEvent,

    /**
     * The GanttChartModelEvent model constructor.
     * @property {module:model/GanttChartModelEvent}
     */
    GanttChartModelEvent,

    /**
     * The ScheduledTask model constructor.
     * @property {module:model/ScheduledTask}
     */
    ScheduledTask,

    /**
     * The SerializableColor model constructor.
     * @property {module:model/SerializableColor}
     */
    SerializableColor,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
